=== Byterset/libdragon_tiny3d_test/tools/material-schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "title": "Schema for an N64 material",
    "definitions": {
        "texture": {
            "oneOf": [
                {
                    "type": "string",
                    "description": "the Path of the texture"
                },
                {
                    "type": "object",
                    "description": "Texture definition including tex Params",
                    "properties": {
                        "filename": {
                            "type": "string"
                        },
                        "s": {
                            "type": "object",
                            "properties": {
                                "mirror": {
                                    "type": "boolean"
                                },
                                "repeats": {
                                    "type": "integer",
                                    "default": "2048",
                                    "minimum": 0,
                                    "maximum": 2048
                                },
                                "scroll": {
                                    "type": "number"
                                },
                                "translate": {
                                    "type": "integer"
                                },
                                "scale_log": {
                                    "type": "integer"
                                }
                            }
                        },
                        "t": {
                            "type": "object",
                            "properties": {
                                "mirror": {
                                    "type": "boolean"
                                },
                                "repeats": {
                                    "type": "integer",
                                    "default": "2048",
                                    "minimum": 0,
                                    "maximum": 2048
                                },
                                "scroll": {
                                    "type": "number"
                                },
                                "translate": {
                                    "type": "integer"
                                },
                                "scale_log": {
                                    "type": "integer"
                                }
                            }
                        },
                        "tmem_addr": {
                            "type": "integer"
                        },
                        "palette": {
                            "type": "integer"
                        },
                        "min_filter": {
                            "type": "string",
                            "default": "nearest",
                            "enum": [
                                "nearest",
                                "linear"
                            ]
                        },
                        "mag_filer": {
                            "type": "string",
                            "default": "nearest",
                            "enum": [
                                "nearest",
                                "linear"
                            ]
                        },
                        "sequenceLength": {
                            "type": "integer"
                        }
                    },
                    "required": [
                        "filename"
                    ]
                }
            ]
        },
        "color": {
            "type": "array",
            "items": {
                "type": "integer",
                "minimum": 0,
                "maximum": 255
            },
            "minItems": 4,
            "maxItems": 4
        },
        "blenderCycle": {
            "type": "array",
            "items": [
                {
                    "enum": [
                        "IN",
                        "MEMORY",
                        "BLEND",
                        "FOG"
                    ]
                },
                {
                    "enum": [
                        "IN_A",
                        "FOG_A",
                        "SHADE_A",
                        "ZERO",
                        "0"
                    ]
                },
                {
                    "enum": [
                        "IN",
                        "MEMORY",
                        "BLEND",
                        "FOG"
                    ]
                },
                {
                    "enum": [
                        "INV_MUX_A",
                        "MEMORY_CVG",
                        "ONE",
                        "1",
                        "ZERO",
                        "0"
                    ]
                }
            ]

        },
        "combineMode": {
            "type": "object",
            "properties": {
                "color": {
                    "type": "array",
                    "items": [
                        {
                            "enum": [
                                "COMBINED",
                                "TEX0",
                                "TEX1",
                                "PRIM",
                                "SHADE",
                                "ENV",
                                "NOISE",
                                "1",
                                "0"
                            ]
                        },
                        {
                            "enum": [
                                "COMBINED",
                                "TEX0",
                                "TEX1",
                                "PRIM",
                                "SHADE",
                                "ENV",
                                "CENTER",
                                "K4",
                                "0"
                            ]
                        },
                        {
                            "enum": [
                                "COMBINED",
                                "TEX0",
                                "TEX1",
                                "PRIM",
                                "SHADE",
                                "ENV",
                                "SCALE",
                                "COMBINED_ALPHA",
                                "TEX0_ALPHA",
                                "TEX1_ALPHA",
                                "PRIM_ALPHA",
                                "SHADE_ALPHA",
                                "ENV_ALPHA",
                                "LOD_FRACTION",
                                "PRIM_LOD_FRAC",
                                "K5",
                                "0"
                            ]
                        },
                        {
                            "enum": [
                                "COMBINED",
                                "TEX0",
                                "TEX1",
                                "PRIM",
                                "SHADE",
                                "ENV",
                                "1",
                                "0"
                            ]
                        }
                    ]
                },
                "alpha": {
                    "type": "array",
                    "items": [
                        {
                            "enum": [
                                "COMBINED_ALPHA",
                                "TEX0_ALPHA",
                                "TEX1_ALPHA",
                                "PRIM_ALPHA",
                                "SHADE_ALPHA",
                                "ENV_ALPHA",
                                "1",
                                "0"
                            ]
                        },
                        {
                            "enum": [
                                "COMBINED_ALPHA",
                                "TEX0_ALPHA",
                                "TEX1_ALPHA",
                                "PRIM_ALPHA",
                                "SHADE_ALPHA",
                                "ENV_ALPHA",
                                "1",
                                "0"
                            ]
                        },
                        {
                            "enum": [
                                "TEX0_ALPHA",
                                "TEX1_ALPHA",
                                "PRIM_ALPHA",
                                "SHADE_ALPHA",
                                "ENV_ALPHA",
                                "LOD_FRACTION",
                                "PRIM_LOD_FRAC",
                                "0"
                            ]
                        },
                        {
                            "enum": [
                                "COMBINED_ALPHA",
                                "TEX0_ALPHA",
                                "TEX1_ALPHA",
                                "PRIM_ALPHA",
                                "SHADE_ALPHA",
                                "ENV_ALPHA",
                                "1",
                                "0"
                            ]
                        }
                    ]
                }
            }
        }
    },
    "type": "object",
    "properties": {
        "combineMode": {
            "anyOf": [
                {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/combineMode"
                    },
                    "maxLength": 2,
                    "minLength": 2
                },
                {
                    "$ref": "#/definitions/combineMode"
                }
            ]
        },
        "tex0": {
            "anyOf": [
                {
                    "$ref": "#/definitions/texture"
                },
                {
                    "type": "string"
                }
            ]
        },
        "tex1": {
            "anyOf": [
                {
                    "$ref": "#/definitions/texture"
                },
                {
                    "type": "string"
                }
            ]
        },
        "envColor": {
            "$ref": "#/definitions/color"
        },
        "primColor": {
            "$ref": "#/definitions/color"
        },
        "blendColor": {
            "$ref": "#/definitions/color"
        },
        "lighting": {
            "type": "boolean"
        },
        "vertexGamma": {
            "type": "number"
        },
        "blendMode": {
            "anyOf": [
                {
                    "type": "string",
                    "description": "A string representing one of the preset blend modes.",
                    "default": "OPAQUE",
                    "enum": ["OPAQUE", "TRANSPARENT", "ALPHA_CLIP", "ADD"]
                },
                {
                    "type": "object",
                    "description": "Custom blend mode",
                    "properties": {
                        "cyc1": {
                            "$ref": "#/definitions/blenderCycle"
                        },
                        "cyc2": {
                            "$ref": "#/definitions/blenderCycle"
                        },
                        "zMode": {
                            "type": "string",
                            "enum": ["OPAQUE", "INTER", "TRANSPARENT", "DECAL"]
                        },
                        "zWrite": {
                            "type": "boolean"
                        },
                        "zCompare": {
                            "type": "boolean"
                        }
                    },
                    "required": ["cyc1", "zMode"]
                }
            ]
        },
        "culling": {
            "type": "boolean"
        },
        "zBuffer": {
            "type": "boolean"
        }

    },
    "required": ["tex0", "combineMode", "blendMode"],
    "additionalProperties": false
}

=== Byterset/libdragon_tiny3d_test/assets/materials/fire/fire.mat.json
{
    "tex0": {
        "filename": "../../images/fire/fire32bit.png",
        "t": {
            "scroll": 0.9
        }
    },
    "combineMode": [{
        "color": ["TEX0", "0", "PRIM", "0"],
        "alpha": ["TEX0_ALPHA", "0", "PRIM_ALPHA", "0"]
    }],
    "primColor": [255, 255, 255, 255],
    "blendMode": "TRANSPARENT",
    "zBuffer": true
}

=== Byterset/libdragon_tiny3d_test/assets/materials/spell/fire_particle.mat.json
{
    "tex0": {
        "filename": "../../images/spell/fire_particle.png",
        "s": {
            "repeats": 0,
            "mirror": false
        },
        "t": {
            "repeats": 0,
            "mirror": false
        }
    },
    "combineMode": [{
        "color": ["TEX0", "0", "PRIM", "0"],
        "alpha": ["TEX0", "0", "PRIM", "0"]
    }],
    "primColor": [255, 255, 255, 255],
    "blendMode": "ALPHA_CLIP",
    "zBuffer": true
}
